In [2]:
import pandas as pd
import numpy as np

In [3]:
df_nearby = pd.read_json("assets/location-cep-nearby.json", convert_axes=False, orient="index")
df_properties = pd.read_json("assets/olx_location_cep_price.json",orient="records", convert_dates=False)

df_nearby.head()

,49044350,49025100,49095815,49037130,49020470,49088000,49025193,49045706,49026196,49095809,...,49037450,49080300,49087420,49020160,49044316,49048523,49043510,49037026,49037720,49092696
formatted_address,"Aracaju, SE, Brasil","Jardins, Aracaju - SE, 49025-100, Brasil","Aracaju - SE, 49095-815, Brasil","Atalaia, Aracaju - SE, 49037-130, Brasil","Rua Américo Curvelo - Salgado Filho, Aracaju -...","Av. Lamarão - Lamarão, Aracaju - SE, 49088-000...","Aracaju, SE, Brasil","Aracaju - SE, 49045-706, Brasil","R. Anna Dulce Vieira de Carvalho - Jardins, Ar...","Jabutiana, Aracaju - SE, 49095-809, Brasil",...,"Atalaia, Aracaju - SE, 49037-450, Brasil","América, Aracaju - SE, 49080-300, Brasil","Dezoito do Forte, Aracaju - SE, 49087-420, Brasil","Salgado Filho, Aracaju - SE, 49020-160, Brasil","Terra Dura, Aracaju - SE, 49044-316, Brasil","Luzia, Aracaju - SE, 49048-523, Brasil","Aracaju, SE, Brasil","R. Agenor Costa Vieira - Aeroporto, Aracaju - ...","Aeroporto, Aracaju - SE, 49037-720, Brasil","Rua Três - Olaria, Aracaju - SE, 49092-696, Br..."
geometry,"{'location': {'lat': -10.9472468, 'lng': -37.0...","{'location': {'lat': -10.9396559, 'lng': -37.0...","{'location': {'lat': -10.9299886, 'lng': -37.0...","{'location': {'lat': -10.9926775, 'lng': -37.0...","{'location': {'lat': -10.9282507, 'lng': -37.0...","{'location': {'lat': -10.8726535, 'lng': -37.0...","{'location': {'lat': -10.9472468, 'lng': -37.0...","{'location': {'lat': -10.939723, 'lng': -37.06...","{'location': {'lat': -10.9497925, 'lng': -37.0...","{'location': {'lat': -10.9409589, 'lng': -37.0...",...,"{'location': {'lat': -10.9858027, 'lng': -37.0...","{'location': {'lat': -10.9146651, 'lng': -37.0...","{'location': {'lat': -10.9036168, 'lng': -37.0...","{'location': {'lat': -10.9290167, 'lng': -37.0...","{'location': {'lat': -10.9919897, 'lng': -37.1...","{'location': {'lat': -10.9391225, 'lng': -37.0...","{'location': {'lat': -10.9472468, 'lng': -37.0...","{'location': {'lat': -10.9906689, 'lng': -37.0...","{'location': {'lat': -10.987701, 'lng': -37.06...","{'location': {'lat': -10.8999632, 'lng': -37.1..."
location_name,Aracaju,49025-100,49095-815,49037-130,49020-470,49088-000,Aracaju,49045-706,49026-196,49095-809,...,49037-450,49080-300,49087-420,49020-160,49044-316,49048-523,Aracaju,49037-026,49037-720,49092-696
photos,"[{'height': 3120, 'html_attributions': ['<a hr...",None,None,None,None,None,"[{'height': 3120, 'html_attributions': ['<a hr...",None,None,None,...,None,None,None,None,None,None,"[{'height': 3120, 'html_attributions': ['<a hr...",None,None,None
nearby_results,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...,[{'geometry': {'location': {'lat': -10.9472468...

In [4]:
import re

def find_related_nearby_location(cep):
    formatted_cep = re.sub('[^0-9]', '', cep)
    nearby_location = df_nearby[formatted_cep]["nearby_results"]
    return nearby_location

df_properties["caracteristicas"].head().apply(pd.Series)["cep"].apply(find_related_nearby_location)

0    [{'geometry': {'location': {'lat': -10.9472468...
1    [{'geometry': {'location': {'lat': -10.9472468...
2    [{'geometry': {'location': {'lat': -10.9472468...
3    [{'geometry': {'location': {'lat': -10.9472468...
4    [{'geometry': {'location': {'lat': -10.9472468...
Name: cep, dtype: object

In [5]:
df_properties["nearby_locations"] = df_properties["caracteristicas"].apply(pd.Series)["cep"].apply(find_related_nearby_location)

df_properties["nearby_locations"]

0       [{'geometry': {'location': {'lat': -10.9472468...
1       [{'geometry': {'location': {'lat': -10.9472468...
2       [{'geometry': {'location': {'lat': -10.9472468...
3       [{'geometry': {'location': {'lat': -10.9472468...
4       [{'geometry': {'location': {'lat': -10.9472468...
                              ...
5074    [{'geometry': {'location': {'lat': -10.9472468...
5075    [{'geometry': {'location': {'lat': -10.9472468...
5076    [{'geometry': {'location': {'lat': -10.9472468...
5077    [{'geometry': {'location': {'lat': -10.9472468...
5078    [{'geometry': {'location': {'lat': -10.9472468...
Name: nearby_locations, Length: 5079, dtype: object

In [6]:
# df_properties.to_json("assets/olx_location_cep_nearby.json", orient="records")

In [7]:
df_saved = pd.read_json("assets/olx_location_cep_nearby.json", orient="records", convert_dates=False)

In [8]:
for i in df_saved["nearby_locations"][0]:
    if "business_status" in i:
        print(i["name"],i["types"])

Ednardo Marques | Arquiteto ['point_of_interest', 'establishment']
Banco24Horas ['atm', 'finance', 'point_of_interest', 'establishment']
IN OUT MKT ['point_of_interest', 'establishment']
Click Marketing Digital ['point_of_interest', 'establishment']
Curos de Programação ['point_of_interest', 'establishment']
Igreja Universal ['church', 'place_of_worship', 'point_of_interest', 'establishment']
CBN Sergipe ['church', 'place_of_worship', 'point_of_interest', 'establishment']
Clínica Veterinária Mundo Animal ['veterinary_care', 'point_of_interest', 'establishment']
Criativo Gesso ['general_contractor', 'point_of_interest', 'establishment']
Teatro Tobias Barreto ['point_of_interest', 'establishment']
Ricardo Marques ['point_of_interest', 'establishment']
Dra. Ilma dos Santos Viana, Cirurgião vascular ['doctor', 'health', 'point_of_interest', 'establishment']
Healthy Gourmet ['restaurant', 'food', 'point_of_interest', 'establishment']
Delta serralheria ['point_of_interest', 'establishment']
Outstanding Consultoria Ambiental ['point_of_interest', 'establishment']
Estrutura e Objetos ['point_of_interest', 'establishment']
Solução Refrigeração ['general_contractor', 'point_of_interest', 'establishment']
Delícia da Juliana ['bakery', 'food', 'point_of_interest', 'store', 'establishment']

In [9]:
attributes_selected = [
#    physical
    'tourist_attraction', 'local_government_office', 'fire_station', 'park', 'police',
#   Social
    'church', 'gym', 'library', 'movie_theater', 'university', 'school', 'night_club',
#   Economical
    'finance', 'bank', 'bar', 'restaurant', 'drugstore', 'gas_station', 'store', 'supermarket', 'hospital', 
#   Traffic
    'transit_station', 'bus_station', 'taxi_stand',
]

In [10]:
all_types = []

for neabies_property in df_saved["nearby_locations"]:
    for element in neabies_property:
        if 'types' in element:
            for tp in element['types']:
                all_types.append(tp)
            
df_types = pd.DataFrame(all_types)

In [11]:
df_types.head()

                   0
0           locality
1          political
2  point_of_interest
3      establishment
4                atm

In [15]:
print("len unique: " + str(len(df_types[0].unique())))
df_types[0].unique()

df_count = df_types[0].value_counts()
df_available_points = pd.DataFrame(df_count).head(20)

len unique: 96

In [24]:
list(df_available_points.index)

['point_of_interest',
 'establishment',
 'store',
 'political',
 'food',
 'health',
 'clothing_store',
 'sublocality_level_1',
 'sublocality',
 'locality',
 'finance',
 'restaurant',
 'home_goods_store',
 'general_contractor',
 'lodging',
 'place_of_worship',
 'church',
 'electronics_store',
 'school',
 'beauty_salon']